// Before publishing your new repository:
// 1. Write the readme file
// 2. Update the issues link in Contributing section in the readme file
// 3. Update the discussion link in config.yml file in .github/ISSUE_TEMPLATE directory

= poj_01 - Teragrep Pooling Library for Java

// Add a short description of your project. Tell what your project does and what it's used for.

This library is designed to allow reusing resources  using a Pool. The Pool can be initialized with a Supplier, that supplies the resource. The supplier is used to create a new resource, if there
are no available resources already in the Pool.
This is useful especially in memory structures, such as MemorySegments or network connections.

== Features

// List your project's features
* Poolable interface, to be implemented by the reusable resource object.
* Pool interface, which is implemented by the included UnboundPool.
* PoolableSupplier, which is to be implemented by the resource supplier.
** The supplier contains the `void accept(T)` and `T apply( R)` methods provided by Java Function and Consumer interfaces. The accept() function is to be used when the
Pool is closing to free or deallocate any of the resources in use by the Poolable. The apply() function is used to supply the new resource, and it also provides a reference
to the Pool, which called the function.

== Documentation

See the official documentation on https://docs.teragrep.com[docs.teragrep.com].

== How to compile

The project can be compiled using Maven and Java 8+ version.

[source,bash]
----
JAVA_HOME=/usr/lib/jvm/temurin-8-jdk mvn clean package
----
== How to use

* Create a Supplier implementing the PoolableSupplier interface.
* Create a Poolable with an implementation and a stub object.
* Initialize the pool using the created objects.
* You can get new Poolables or recycled Poolables from the Pool with the get() method.
* Try-with-resources can be used to automatically close the resources.
* See example below.

[source,java]
----
import com.teragrep.poj_01.pool.Pool;
import com.teragrep.poj_01.pool.PoolableSupplier;
import com.teragrep.poj_01.pool.UnboundPool;

void example() {
    final PoolableSupplier<Pool<Poolable>, Poolable> supplier = new PoolableSupplierImpl();
    final Poolable poolableStub = new PoolableStub();

    try (Pool<Poolable> pool = new UnboundPool<>(supplier, poolableStub)) {
           try (final Poolable poolable = pool.get()) {
                // do stuff with poolable
                // try-with-resources will call close() on poolable, returning it to pool.
           }
           // try-with-resources will call close() on pool, deallocating poolable resources and closing the pool.
    }


}
----


== Contributing

// Change the repository name in the issues link to match with your project's name

You can involve yourself with our project by https://github.com/teragrep/poj_01/issues/new/choose[opening an issue] or submitting a pull request.

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories.

You need to submit the CLA only once. After submitting the CLA you can contribute to all Teragrep's repositories.
